version: 2
sources:
  - name: raw
    schema: gz_raw_data
    description: base de donnees de greenweez donne par la teamfinance
    tables:
      - name: product
        identifier: raw_gz_product
      - name: sales
        identifier: raw_gz_sales
      - name: ship
        identifier: raw_gz_ship

